### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by chillex0** [Chiel92/fontdozenalizer#1]
I downloaded and extracted the .zip, but when I went to copypaste this "python3 -m pip install -r requirements.txt
" into PowerShell (modern equivalent of cmd, not sure if that affects anything) from the folder where I extracted the .zip to, it gave me this series of messages:
![image](https://user-images.githubusercontent.com/47342134/127399990-6ae24158-9285-4dbc-aa3c-e73d0b6d01a2.png)
After this, I tried to copypaste this "$ python3 addglyphs.py Arial.ttf ArialDozenalized.ttf
" into Python and it gave me this (probably related to what caused the first error)
![image](https://user-images.githubusercontent.com/47342134/127400433-6f00a3eb-8954-4e6b-bc1d-40a6edbae2dd.png)

**Comment by chtenb** [comment]
The second error is easy to fix: you are pasting the command in the wrong prompt. You have the python interpreter prompt open, which is for typing python code, not for running programs. Instead you should have pasted it in the first prompt (the blue one), and without the **$**.

With a bit of luck that works, but if not you should probably attend to the first error. Try installing the c++ redistributable like it suggests, which is a very common piece of software needed for many programs.

**Comment by chillex0** [comment]
Installing C++ got rid of the first error, but now I get a 'gvar' error.
![image](https://user-images.githubusercontent.com/47342134/127407471-8c114feb-ce6d-4d8d-b09c-0b831be4ad8d.png)

**Comment by chtenb** [comment]
Can you link me to the font file you are using? So I can reproduce it myself.

**Comment by chillex0** [comment]
It is the same font as your example: Arial.
[arial.zip](https://github.com/dznl/fontdozenalizer/files/6896976/arial.zip)

**Comment by chillex0** [comment]
Have you been able to detect the problem? Or did you recreate it with no issues?

**Comment by chtenb** [comment]
For some reason github did not notify me of your reply with the zip. I will look at it today or tomorrow.

**Comment by chtenb** [comment]
I've reproduced and fixed the issue in the latest commit.
![image](https://user-images.githubusercontent.com/1030961/128506314-3301a474-d9a8-4b2a-9441-5250b8804c9f.png)
